name: '[prod] Deploy qubetics docs'

on: 
  push:
    branches: 
      - main

jobs:
  deploy_qubetics_docs_service:
    uses: ./.github/workflows/qubeticsdocs-service.yaml
    with:
      SWR_ORGANIZATION: prod-qubetics
      ARGOCD_BRANCH: prod
      HUAWEI_REGION: 'ap-southeast-1'
      ARGOCD_REPOSITORY: Qubetics/argocd-qubetics
      DEPLOYMENT_PATH: Qubetics-docs/qubeticsdocs-deployment.yaml
      HUAWEI_IMAGE: qubeticsdocs
      DOCKER_USERNAME: ap-southeast-1@QHAEGIBURQMR6N4X3NQW
      ENV: ${{ vars.PROD_QUBETICS_DOCS_ENV }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GIT_SSH_KEY: ${{ secrets.ARGOCD_SSH_KEY }}
